services:
  server:
    build: ./server   # your backend folder
    ports:
      - "5000:5000"
    networks:
      - app-network

  client:
    build: ./client   # your frontend folder
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge